### ISSUE TITLE
Scale to Fit Grid Layout?

### ISSUE THREAD

**Issue by efaden** [pkissling/clock-weather-card#112]
I am trying to make a grid-layout that has fixed dimensions.  For right now I have a grid layout with 4 columns and 4 rows.  The grid layout is set to 100% of the screen.  I am placing the clock-weather-card along the top using a grid-area.  It doesn't seem to mater what I specify the clock-weather-card grows well outside of the size of the row. I can't figure out what to modify with card-mod top make it stay within its bounds.  Any help appreciated..... here is an example of my code and in image.  If you look at the image you can see that the top set of boxes is the grid area.... but as you can also see the clock-weather-card is well outside of those boxes.  Thanks

  ```
- title: New
    path: new-new
    type: custom:grid-layout
    layout:
      height: calc(100vh - 64px)
      width: 100%
      margin: 0
      grid-gap: 15px
      grid-template-columns: 1fr 1fr 1fr 1fr
      grid-template-rows: 100px 1fr 1fr 1fr
      grid-template-areas: |
        "header header header header"
        ". . . ."
        ". . . ."
        "footer . . ."
    cards:
      - type: custom:mod-card
        view_layout:
          grid-area: header
        card:
          type: grid
          columns: 1
          square: false
          cards:
            - type: custom:clock-weather-card
              entity: weather.openweathermap
      - type: custom:mod-card
        view_layout:
          grid-area: footer
        card:
          type: grid
          columns: 1
          square: false
          cards:
            - type: custom:button-card
              entity: switch.lamp1

```

<img width="966" alt="Screen Shot 2022-11-14 at 8 55 33 AM" src="https://user-images.githubusercontent.com/12599300/201677883-80f1bfa0-266e-489e-b099-8e40406bda7a.png">

**Comment by pkissling** [comment]
hi there, neither have i access to a laptop until the end of the year due to vacation, nor do i habe any knowledge about `grid-layout` and `mod-card`.
i'm afraid i won't be able to help  you on this matter for now

**Comment by efaden** [comment]
No worries.  Basically I'm just trying to specify the maximum height of the card and have it scale to that.  As it is right now as the tablet gets wider the card gets taller and taller.  It's taking up almost 1/3 of the tablet screen

**Comment by pkissling** [comment]
hi there, is this issue still relevant?
i tried reproducing the issue, but i'm not able to.
clock-weather-card makes itself fit into the corresponding grid
though in the snippet you provided i see that you are using `custom:mod-card`, which i couldn't find in hacs. i found `card-mod`, but thats a different plugin.
<img width="1560" alt="Screenshot 2023-01-31 at 18 55 09" src="https://user-images.githubusercontent.com/33731393/215843823-9a83514d-d95b-4d53-82f9-a3434375b2cf.png">

**Comment by pkissling** [comment]
hi @efaden,
is it possbile that the issue you describe is related to how the card is configured?
i took some time to play around with `grid-layout` and the behaviour you describe basically applies to all components i used (even the default HA components like `type: entities`.
<img width="1581" alt="Screenshot 2023-01-31 at 19 04 23" src="https://user-images.githubusercontent.com/33731393/215845812-40d29583-7f50-4e54-a494-186b782d1045.png">

i was somewhat able to get the layout you describe by omitting the `card-mod` section altogether
<img width="1560" alt="Screenshot 2023-01-31 at 18 55 09" src="https://user-images.githubusercontent.com/33731393/215845956-f44a3e9d-9933-47de-b10e-24f99bd64400.png">
```
- path: home
  icon: mdi:home
  type: custom:grid-layout
  layout:
    height: calc(100vh - 64px)
    width: 100%
    margin: 0
    grid-gap: 15px
    grid-template-columns: 1fr 1fr 1fr 1fr
    grid-template-areas: |
      "header header header header"
      ". . . ."
      ". . . ."
      "footer . . ."
  cards:
    - type: custom:clock-weather-card
      entity: weather.home
      date_pattern: dd.MM.yyyy
   # ...
```
