### ISSUE TITLE
Change Tap Action

### ISSUE THREAD

**Issue by Danit2** [pkissling/clock-weather-card#117]
**Is your feature request related to a problem? Please describe.**

it would be great if you could change the tap_action.  like other cards.

**Comment by msolomos** [comment]
tap action is a must! please consider it

**Comment by jensrossbach** [comment]
I totally agree, I would like to navigate to another page when the weather card is clicked.

**Comment by msolomos** [comment]
is not just that! You want to show more weather data.- 
And the logic says thay you must cllick a weather card to see more weather data. 

![web](https://github.com/pkissling/clock-weather-card/assets/72358278/df91f8db-cdd3-43d2-8fcf-8cf8b2d0ee4f)

**Comment by a-kildahl** [comment]
I'd like the tab_action to just take me to the official OpenWeatherForecast website for my city, so I can get very granular weather data.

**Comment by fgonza2** [comment]
is this now available? how can i navigate to another view when i tap?

**Comment by fgonza2** [comment]
looks like it works now, i entered:

`tap_action:
  action: navigate
  navigation_path: /lovelace/weather`

and it takes me to another card where i have all the weather stuff.   Som we are good  :)

**Comment by nickt444** [comment]
What am I missing? When I click anything in the card, it just returns the data from the configured entity.
Here is my config:

type: custom:clock-weather-card
entity: weather.<redacted>
forecast_rows: 7
show_humidity: true
humidity_sensor: sensor.shelly_h_t_ca9333_humidity
show_decimal: true
tap-action:
  action: navigate
  navigate_path: /dashboard-weather/0

The navigate_path is the path after my FQDN. I have also tried url_path with https://<fqdn>:8123/dashboard-weather/0 and it gives the same result.

**Comment by amaciuc** [comment]
Any news about tap action?

**Comment by fabsau** [comment]
for me this works:
```yaml
type: custom:clock-weather-card
entity: weather.openweathermap
title: null
sun_entity: sun.sun
temperature_sensor: sensor.openweathermap_temperature
humidity_sensor: sensor.openweathermap_humidity
weather_icon_type: fill
animated_icon: true
forecast_rows: 3
locale: en-GB
time_pattern: HH:mm
time_format: 24
date_pattern: cccc, dd.MM
hide_today_section: false
hide_forecast_section: false
show_humidity: false
hide_clock: false
hide_date: true
hourly_forecast: true
use_browser_time: false
time_zone: null
show_decimal: true
apparent_sensor: sensor.openweathermap_feels_like_temperature
aqi_sensor: null
tap_action:
  action: navigate
  navigation_path: "#weather"

``` 

I'm using btw bubble card for the popup, but any navigation path should be working
