### ISSUE TITLE
Not displaying the right values for temperature for met.no

### ISSUE THREAD

**Issue by FenvyWorks** [pkissling/clock-weather-card#15]
Seems like it doesn't work with met.no forecast for some reason.

![Capture](https://user-images.githubusercontent.com/39421725/196235179-2fdddaa2-cac4-4f20-9356-1cd605e05e0c.PNG)

**Comment by FenvyWorks** [comment]
The right values in atributes would be

temperature: 28
humidity: 56
pressure: 1016.8
wind_bearing: 57.9
wind_speed: 19.1
forecast:
  - condition: rainy
    precipitation: 2.7
    temperature: 27.8
    templow: 21.4
    datetime: '2022-10-18T15:00:00+00:00'
    wind_bearing: 66.5
    wind_speed: 21.2
  - condition: rainy
    precipitation: 1
    temperature: 27.8
    templow: 21.1
    datetime: '2022-10-19T15:00:00+00:00'
    wind_bearing: 54.2
    wind_speed: 26.3

**Comment by pkissling** [comment]
so this is not an issue anymore?

**Comment by FenvyWorks** [comment]
Oh it still is, at least for the version published and available on HACS. I apologize for not making things clear.

**Comment by pkissling** [comment]
i just tested the met.no integration with the latest published clock-weather-card version (1.0.3).
for my side it looks fine. 
![image](https://user-images.githubusercontent.com/33731393/196461598-c1a159a5-3a3d-4db7-868f-9f2076f11c97.png)

my hunch is that the data delivered by met.no might differ depending on your location (lat/long).
```
temperature: 20.3
temperature_unit: °C
humidity: 61
pressure: 1025.8
pressure_unit: hPa
wind_bearing: 274.4
wind_speed: 14
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast: 
- condition: cloudy
  datetime: '2022-10-19T10:00:00+00:00'
  wind_bearing: 54.5
  temperature: 16.3
  templow: 10.2
  wind_speed: 11.9
  precipitation: 0
- condition: cloudy
  datetime: '2022-10-20T10:00:00+00:00'
  wind_bearing: 77
  temperature: 18
  templow: 7.7
  wind_speed: 11.9
  precipitation: 0
- condition: rainy
  datetime: '2022-10-21T10:00:00+00:00'
  wind_bearing: 136.9
  temperature: 17.3
  templow: 10.4
  wind_speed: 11.2
  precipitation: 6.3
- condition: partlycloudy
  datetime: '2022-10-22T10:00:00+00:00'
  wind_bearing: 269.3
  temperature: 16.7
  templow: 10.9
  wind_speed: 11.5
  precipitation: 1.5
- condition: cloudy
  datetime: '2022-10-23T10:00:00+00:00'
  wind_bearing: 100.1
  temperature: 20.3
  templow: 8
  wind_speed: 12.2
  precipitation: 0.1

attribution: Weather forecast from met.no, delivered by the Norwegian Meteorological Institute.
friendly_name: Forecast Home
```

could you provide your lat/long to hopefully make me able to reproduce the problem?
