### ISSUE TITLE
Removal of temperature ‘dot’

### ISSUE THREAD

**Issue by leacho73** [pkissling/clock-weather-card#192]
Apologies if I’ve glanced over the docs and missed this - but is it possible to remove the ‘dot’ on the current days weather forecast - with my current theming it’s just showing a black dot and it’s hard to see the forecast for the upcoming hours in terms of temperature.

apart from that - an excellent add on - thank you!!

**Comment by pkissling** [comment]
you can easily remove the dot using card-mod:
```yaml
- type: custom:clock-weather-card
  # ...
  card_mod:
    style: |
      forecast-temperature-bar-current-indicator-dot {
        visibility: hidden !important;
      }
```
