### ISSUE TITLE
Make clock font-width grow dynamically

### ISSUE THREAD

**Issue by pkissling** [pkissling/clock-weather-card#34]
Currently the font-size of the clock is set to a fixed value. Depending on the resolution and viewport, there is a lot of wasted space.

Task: Find a solution to make the clock font-size grow dynamically with the space of the surrounding div.
Options:
* Calculate font-size dynamically based on width of surrounding div
* Render text as svg

**Comment by netmanchris** [comment]
Let me know if I should open another issue, but It would be great to be able to set the font size of the clock in the YAML definition when adding this card to a dashboard.  

In the mean time - Can you point me towards where in the JS file the clock size is statically configured so I can change it manually? 

Really appreciate the great work!  Loving this card!

**Comment by joevberg** [comment]
I've tried changing everything in the js to no avail

**Comment by pkissling** [comment]
hi there,

you can easily change the font size yourself using [card-mod](https://github.com/thomasloven/lovelace-card-mod):

```yaml
- type: custom:clock-weather-card
  entity: weather.home
  style: |
    clock-weather-card-today-right-wrap-center {
      font-size: 20rem !important;
    }
```
