### ISSUE TITLE
Request for customized weather forecast for specific dates and customizable color for the bottom temperature bar.

### ISSUE THREAD

**Issue by maodun96** [pkissling/clock-weather-card#404]
**Is your feature request related to a problem? Please describe.**

The color of the bottom temperature bar is not consistent with the customized lovelace panel style, so I hope to be able to customize the color of the temperature bar.
My weather entity provides yesterday's weather conditions. It will be displayed in this card as well. So I hope to be able to specify the weather for the "future" days.

**Describe the solution you'd like**

I hope to be able to customize the color of the temperature bar. Able to specify the weather for the "future" days.

**Describe alternatives you've considered**

I've thought about using card mod to change the color of the temperature bar. creating a new weather entity, and mapping the future weather forecast (to eliminate yesterday's weather). I haven't tried it yet.

**Additional context**
![image](https://github.com/pkissling/clock-weather-card/assets/43996175/f5e1e50c-5ded-479c-aa7b-4e872d6ccdc8)

**Comment by pkissling** [comment]
hi @maodun96,
regarding the issue that your card is showing yesterdays weather: this is an issue of your weather provider publishing past forecasts. the card simply displays the forecast provided by the weather integration.
regarding the background of the temperature bars: feel free to override the css using card-mod:
```yaml
- type: custom:clock-weather-card
  # ...
  card_mod:
    style: |
      forecast-temperature-bar-background {
        background: transparent !important;
      }
```
