### ISSUE TITLE
Tap Action to switch between daily and hourly forecasts

### ISSUE THREAD

**Issue by Zerosignal84** [pkissling/clock-weather-card#490]
It would be great to be able to tap the card and switch between the daily and hourly forecast data, I tried to implement a tap action on the card to trigger a sensor but the tap action was not overriding the default.

Perhaps it could be possible to build in to the core of the card the ability to receive the hourly and daily data feeds with as tap on the card allowing you to switch from daily to hourly forecast data.

**Comment by LGH531** [comment]
You can do this by creating 2 cards (Daily, Hourly) both with a tap action to toggle an input_boolean, and then use the visibility conditions to control each card.

**Comment by Markoslager** [comment]
I have been trying to assign a tap action to this card myself, but i can't make it work.
Does this card support tap_action?

**Comment by LGH531** [comment]
> I have been trying to assign a tap action to this card myself, but i can't make it work. Does this card support tap_action?

I got tap action to work for me.

**Comment by Zerosignal84** [comment]
It didn’t work for me when trying that is why I was here asking for a solution as I had the same idea you had.

If you don’t mind sharing, what is the yaml that you used for the card to get it working?

**Comment by Zerosignal84** [comment]
Ok so I got this to work with the following YAML and an input_boolean - thanks for the suggestion LGH.

```
type: custom:clock-weather-card
entity: weather.
sun_entity: sun.sun
title: 
forecast_rows: 5
time_format: 12
weather_icon_type: fill
show_humidity: true
show_decimal: true
tap_action:
  action: call-service
  service: input_boolean.toggle
  service_data:
    entity_id: input_boolean.clock_weather_card_switch
visibility:
  - condition: state
    entity: input_boolean.clock_weather_card_switch
    state: "off"
```
