### ISSUE TITLE
Align weather time and date

### ISSUE THREAD

**Issue by KaportsevIA** [pkissling/clock-weather-card#99]
It is necessary to center the weather, time and date in the card. In the current version, it does not look very nice.
![Снимок экрана 2022-10-31 133200](https://user-images.githubusercontent.com/98884453/198988431-13b5285e-cf15-4c6e-8b4f-36923e596ce7.jpg)

**Comment by pkissling** [comment]
hi @KaportsevIA, can you propose a solution? i don't quiet understand the problem statement

**Comment by brainfrz82** [comment]
I came here for the same request, the text should be center-alligned (imho). So like this:
![image](https://user-images.githubusercontent.com/26366427/199040115-b1a17367-983a-42d6-b52c-fcd504a85474.png)
Would love to see that as an option, thank you for this great card!

**Comment by pkissling** [comment]
hi @brainfrz82, thanks for the explanation.
it was a design design to make the weather info stick `right`, the clock `center` and the weather `left`.
it pretty much depends on your resolution/viewport on how the card is eventually rendered. on a "regular" screen, it looks pretty okay and i want to keep it that way
![image](https://user-images.githubusercontent.com/33731393/199049456-15554acf-59e6-44a4-ac46-de78df059531.png)

still, if you want to modify the appearance, feel free to use `card-mod` to customize that card to your liking:
```yaml
- type: custom:clock-weather-card
  entity: weather.home
  date_pattern: dd.MM.yyyy
  style: |
    clock-weather-card-today-right-wrap-top {
      justify-content: center !important;
    }
    clock-weather-card-today-right-wrap-bottom {
      justify-content: center !important;
    }
```
and the result:
![image](https://user-images.githubusercontent.com/33731393/199049706-1e6d72de-f804-46d4-89a8-8148301d5e57.png)
